on:
  workflow_dispatch:
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run sh
              run: sh ./v4/install.sh
